import {EQUIPMENT,readLoadout} from './equipment.mjs';
export const PRICES={common:0,rare:80,unique:180,mythic:350,relic:600};
export function upgradeCost(item,level){return Math.max(20,Math.round(PRICES[item.rarity]/4))*(level+1);}
export function clearReward(spec){if(spec.kind==='shop')return 0;return (spec.kind==='boss'?50:spec.kind==='elite'?20:10)*spec.chapter;}
export class PizzaWallet{
 constructor(storage){this.storage=storage;this.balance=0;this.receipts=[];this.owned=EQUIPMENT.filter(e=>e.rarity==='common').map(e=>e.id);this.levels={};let legacy=true;try{const v=JSON.parse(storage.getItem('penny-wallet-v1')||'null');if(Number.isSafeInteger(v?.balance)&&v.balance>=0){this.balance=v.balance;this.receipts=Array.isArray(v.receipts)?v.receipts.filter(x=>typeof x==='string'):[];if(Array.isArray(v.owned))legacy=false;if(Array.isArray(v.owned))this.owned=[...new Set([...this.owned,...v.owned.filter(id=>EQUIPMENT.some(e=>e.id===id))])];else this.owned=[...new Set([...this.owned,...Object.values(readLoadout(storage)).filter(Boolean)])];for(const id of this.owned){const n=v.levels?.[id];this.levels[id]=Number.isInteger(n)?Math.max(0,Math.min(5,n)):0;}}}catch{}if(legacy)this.owned=[...new Set([...this.owned,...Object.values(readLoadout(storage)).filter(Boolean)])];}
 purchase(id){const item=EQUIPMENT.find(e=>e.id===id);if(!item||this.owned.includes(id))return {ok:false,message:'이미 보유했거나 없는 장비입니다.'};return this.transact(PRICES[item.rarity],[...this.owned,id],{...this.levels,[id]:0});}
 upgrade(id){const item=EQUIPMENT.find(e=>e.id===id),level=this.levels[id]||0;if(!item||!this.owned.includes(id)||level>=5)return {ok:false,message:'강화할 수 없는 장비입니다.'};return this.transact(upgradeCost(item,level),[...this.owned],{...this.levels,[id]:level+1});}
 transact(cost,owned,levels){if(this.balance<cost)return {ok:false,message:'피자스코어가 부족합니다.'};const balance=this.balance-cost;try{this.storage.setItem('penny-wallet-v1',JSON.stringify({balance,receipts:this.receipts,owned,levels}));}catch{return {ok:false,message:'저장 실패로 거래가 취소되었습니다. 재화는 차감되지 않았습니다.'};}this.balance=balance;this.owned=owned;this.levels=levels;return {ok:true,message:`완료 · 피자스코어 −${cost}`};}
 credit(id,amount){if(typeof id!=='string'||!Number.isSafeInteger(amount)||amount<=0||this.receipts.includes(id))return {added:0,saved:true};if(!Number.isSafeInteger(this.balance+amount))return {added:0,saved:false};this.balance+=amount;this.receipts.push(id);let saved=true;try{this.storage.setItem('penny-wallet-v1',JSON.stringify({balance:this.balance,receipts:this.receipts,owned:this.owned,levels:this.levels}));}catch{saved=false;}return {added:amount,saved};}
}
