import {PRICES,upgradeCost} from './currency.mjs';
import {EFFECTS} from './equipment-effects.mjs';
import {SLOTS,EQUIPMENT,RARITIES,validFor,normalizeLoadout,bonuses,levelBonus,bonusText,readLoadout,saveLoadout} from './equipment.mjs';
export function createEquipmentUI({storage,showModal,hideModal,getState,wallet,onChange}){
 let selected=normalizeLoadout(Object.fromEntries(Object.entries(readLoadout(storage)).filter(([s,id])=>wallet.owned.includes(id)))),active='weapon';
 const item=id=>EQUIPMENT.find(e=>e.id===id);
 const icon=e=>e?`<img src="${e.src}" alt="" width="48" height="48">`:'<span class="empty-slot">＋</span>';
 function renderTitle(){const root=document.getElementById('equipment-slots');root.innerHTML=SLOTS.map(([slot,label])=>{const e=item(selected[slot]);return `<button type="button" data-slot="${slot}" title="${label}: ${e?.name||'비어 있음'}" aria-label="${label}: ${e?.name||'비어 있음'}">${icon(e)}<small>${label}</small></button>`;}).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.slot));}
 function close(){hideModal();renderTitle();document.querySelector(`#equipment-slots [data-slot="${active}"]`)?.focus();}
 function open(slot=active){if(getState()!=='title')return;active=slot;const current=item(selected[slot]);
 showModal(`<span class="eyebrow">STARTING EQUIPMENT</span><h2 id="modal-title">출발 장비 · ${SLOTS.find(s=>s[0]===slot)[1]}</h2><p>보유 피자스코어 ${wallet.balance} · 일반 3종 기본 지급 · 강화 최대 +5, 단계마다 기본 보너스 +10%. 불리한 수치와 고유 효과는 유지됩니다. 출발 후에는 변경할 수 없습니다.<br>신화·유물의 고유 효과는 조건을 만족하면 자동 발동합니다.</p><nav class="equipment-tabs">${SLOTS.map(([s,label])=>`<button data-tab="${s}" aria-pressed="${s===slot}">${label}</button>`).join('')}</nav><p>현재: ${current?.name||'비어 있음'} · ${bonusText(current?levelBonus(current,wallet.levels[current.id]):{})}</p><div class="equipment-list">${EQUIPMENT.filter(e=>validFor(e,slot)).map(e=>{const other=Object.entries(selected).some(([s,id])=>s!==slot&&id===e.id);const owned=wallet.owned.includes(e.id),level=wallet.levels[e.id]||0,cost=upgradeCost(e,level);return `<article class="equipment-item">${icon(e)}<span><small>${RARITIES[e.rarity]} · ${owned?'보유':'미보유'}</small><strong>${e.name} +${level}</strong><small>${bonusText(levelBonus(e,level))}</small>${EFFECTS[e.id]?`<small>${EFFECTS[e.id]}</small>`:''}${owned?`<button data-equip="${e.id}" ${other||selected[slot]===e.id?'disabled':''}>${selected[slot]===e.id?'장착 중':other?'다른 칸 장착 중':'장착'}</button><small>${level<5?'다음: '+bonusText(levelBonus(e,level+1)):'최대 강화'}</small><button data-upgrade="${e.id}" ${level>=5||wallet.balance<cost?'disabled':''}>${level>=5?'강화 완료':`강화 +${level+1} · ${cost} 피자`}</button>`:`<button data-buy="${e.id}" ${wallet.balance<PRICES[e.rarity]?'disabled':''}>구매 · ${PRICES[e.rarity]} 피자</button>`}</span></article>`;}).join('')}</div><p id="equipment-feedback" role="status">전체 장비 합계: ${bonusText(bonuses(selected,wallet.levels))}</p><div class="modal-actions"><button id="unequip" class="secondary">이 칸 해제</button><button id="equipment-done" class="primary">장착 완료</button></div>`,'equipment');
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>open(b.dataset.tab));
 const set=id=>{if(id&&!wallet.owned.includes(id))return;selected=normalizeLoadout({...selected,[slot]:id});const saved=saveLoadout(storage,selected);renderTitle();open(slot);if(!saved)document.getElementById('equipment-feedback').textContent='선택은 적용되었습니다. 저장할 수 없어 페이지를 닫으면 초기화됩니다.';};
 const trade=(id,upgrade)=>{if(getState()!=='title')return;const result=upgrade?wallet.upgrade(id):wallet.purchase(id);onChange();open(slot);document.getElementById('equipment-feedback').textContent=result.message;};
 document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>trade(b.dataset.buy,false));document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>trade(b.dataset.upgrade,true));
 document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>set(b.dataset.equip));document.getElementById('unequip').onclick=()=>set(null);document.getElementById('equipment-done').onclick=close;
 }
 return {renderTitle,close,open,loadout:()=>({...selected})};
}
