import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.mjs';
import {addImpact,releaseCircuit,drawCombatFeel} from '../combat-feel.mjs';
const make=()=>{const g=new Game({random:()=>.5});g.start();return g;};
test('circuit banks 35 percent actual damage and releases once without double modifiers',()=>{const g=make(),e=g.enemies[0];e.hp=500;e.maxHp=500;e.totemWeak=1;g.action('circuit');g.hitEnemy(e,40,0,false,true);assert.equal(e.hp,450);assert.equal(e.circuitDebt,17.5);releaseCircuit(g);assert.equal(e.hp,450);g.freeze=0;releaseCircuit(g);assert.equal(e.hp,432.5);releaseCircuit(g);assert.equal(e.hp,432.5);assert.equal(g.log.events.filter(x=>x.event==='circuit_release').length,1);});
test('dead targets and room changes cannot carry circuit damage',()=>{const g=make(),e=g.enemies[0];g.action('circuit');g.hitEnemy(e,9999);const kills=g.kills;g.freeze=0;releaseCircuit(g);assert.equal(g.kills,kills);g.action('circuit');g.setRoom(1);assert.equal(g.circuitBank,false);assert.ok(g.enemies.every(e=>!e.circuitDebt));});
test('strong hits interrupt regular foes but preserve boss patterns',()=>{const g=make(),e=g.enemies[0];e.state='windup';e.timer=.2;addImpact(g,e,true);assert.equal(e.state,'recover');const timer=e.timer;g.updateEnemy(e,.05);assert.equal(e.timer,timer);g.setRoom(4);const boss=g.enemies[0];boss.state='windup';addImpact(g,boss,true);assert.equal(boss.state,'windup');assert.ok(!boss.stagger);});
test('leverage accelerates attacks and render paths accept all new effects',()=>{const g=make();g.player.hurt=0;g.attack();const normal=g.player.attackCD;g.player.attackCD=0;g.player.comboClock=0;g.action('leverage');g.attack();assert.ok(Math.abs(g.player.attackCD-normal*.85)<1e-9);g.action('circuit');addImpact(g,g.enemies[0],true);g.effects.push({type:'profit',x:100,y:100,facing:-1,life:.2,max:.4});const ctx=new Proxy({},{get:()=>()=>{},set:()=>true});drawCombatFeel(ctx,g);drawCombatFeel(ctx,g,true);});
