import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.mjs';
function setup(){const g=new Game({random:()=>.5});g.start();g.rewardGiven=true;g.enemies=[];g.relic=null;g.terrain.traps=[];g.platforms=[{x:0,y:620,w:2000,h:100,ground:true}];Object.assign(g.player,{x:200,y:620-g.player.h,grounded:true,inv:999});return g;}
function step(g,t,input={}){for(let i=0;i<Math.ceil(t*120);i++)g.update(1/120,input);}
test('held jump rises higher than released jump, including a tap before update',()=>{const long=setup(),short=setup(),tap=setup();for(const g of [long,short,tap])g.action('jump');tap.action('jump_release');step(long,.06);step(short,.06);short.action('jump_release');step(long,.14);step(short,.14);step(tap,.2);assert.ok(long.player.y<short.player.y-25);assert.ok(short.player.y<tap.player.y);});
test('up attack hits above only and one strike cannot damage twice',()=>{const g=setup();const p=g.player;g.enemies=[g.makeEnemy('ghost',p.x,p.y-10),g.makeEnemy('ghost',p.x+75,p.y+p.h)];g.action('attack_up');assert.equal(g.enemies[0].hp,g.enemies[0].maxHp);step(g,.04);assert.ok(g.enemies[0].hp<g.enemies[0].maxHp);assert.equal(g.enemies[1].hp,g.enemies[1].maxHp);const hp=g.enemies[0].hp;step(g,.17);assert.equal(g.enemies[0].hp,hp);});
test('downward hit bounces once, restores dash and logs success; a miss does not',()=>{for(const hit of [true,false]){const g=setup(),p=g.player;Object.assign(p,{y:350,grounded:false,vy:120,jumps:2,dashCD:.8});if(hit)g.enemies=[g.makeEnemy('ghost',p.x,450)];g.action('attack_down');step(g,.04);if(hit){assert.ok(p.vy<0);assert.equal(p.dashCD,0);assert.equal(p.jumps,1);assert.equal(g.log.events.filter(e=>e.event==='pogo_success').length,1);}else{assert.ok(p.vy>0);assert.ok(p.dashCD>0);}}});
test('dash and damage cancel windup; pause freezes it',()=>{for(const mode of ['dash','hurt','pause']){const g=setup(),p=g.player;const e=g.makeEnemy('rubble',p.x+40,620);g.enemies=[e];g.action('attack');if(mode==='dash')g.action('dash');if(mode==='hurt'){p.inv=0;g.hurt(1,0);}if(mode==='pause')g.state='paused';step(g,.1);assert.equal(e.hp,e.maxHp);if(mode==='pause'){assert.equal(p.attackMove.elapsed,0);g.state='playing';step(g,.04);assert.ok(e.hp<e.maxHp);}}});
