import test from 'node:test';
import assert from 'node:assert/strict';
import {TOTEMS} from '../totems.mjs';
import {Game} from '../engine.mjs';
const setup=(ids)=>{const g=new Game({random:()=>.99});g.start();g.state='totems';for(const [i,id]of ids.entries()){g.totems.acquire(id);g.totems.equip(id,i);}g.state='playing';return g;};
const enemy=g=>{const e=g.makeEnemy('boss',400,620);g.enemies=[e];return e;};
test('exploration requires proximity, pauses play, allows exactly three distinct equipped totems',()=>{const g=setup([]);g.action('interact');assert.equal(g.totems.owned.length,0);g.player.x=g.relic.x-15;g.player.y=g.relic.y-28;g.checkRelicPickup();assert.equal(g.state,'relic_choice');assert.equal(g.chooseRelic('double_bottom'),true);assert.equal(g.state,'totems');assert.equal(g.totems.owned[0],'double_bottom');assert.equal(g.totems.equip('double_bottom',0),true);assert.equal(g.totems.equip('double_bottom',1),false);assert.equal(g.totems.equip('cup',1),false);assert.equal(g.totems.equip('double_bottom',3),false);});
test('empty dash does not charge; one actual dash dodges at most once; hit completes bottom',()=>{const g=setup(['double_bottom']);g.player.inv=0;g.action('dash');assert.equal(g.totems.states.double_bottom.n,0);g.hurt(20,0);g.hurt(20,0);assert.equal(g.totems.states.double_bottom.n,1);g.player.dashCD=0;g.action('dash');g.hurt(20,0);const e=enemy(g),hp=e.hp;g.totems.signal('hit',e);assert.equal(e.hp,hp-g.damage()*.6);assert.equal(g.totems.states.double_bottom.cd,12);g.totems.signal('hit',e);assert.equal(e.hp,hp-g.damage()*.6);});
test('double top binds to one target and debuff increases actual damage then expires',()=>{const g=setup(['double_top']),e=enemy(g),other=g.makeEnemy('boss',500,620);g.totems.signal('finisher',e);g.totems.signal('finisher',other);assert.equal(g.totems.states.double_top.n,1);g.totems.signal('finisher',other);g.totems.signal('profit',e);assert.equal(e.totemWeak,undefined);g.totems.signal('profit',other);g.enemies.push(other);const hp=other.hp;g.hitEnemy(other,20);assert.equal(other.hp,hp-25);g.totems.update(6,{});assert.equal(other.totemWeak,0);});
test('flag needs a release and cup needs dash after formation; damage invalidates cup',()=>{const g=setup(['flag','cup']),e=enemy(g);for(let i=0;i<3;i++)g.totems.signal('hit',e);g.totems.update(1,{attack:true});g.totems.signal('hit',e);assert.equal(g.totems.states.flag.cd,0);g.totems.update(1,{attack:false});g.totems.signal('hit',e);assert.equal(g.totems.states.flag.cd,10);g.totems.signal('hit',e);assert.equal(g.totems.states.cup.n,6);g.totems.signal('hit',e);assert.equal(g.totems.states.cup.cd,0);g.totems.signal('dash');g.totems.signal('hit',e);assert.equal(g.totems.states.cup.cd,16);g.totems.update(16,{});g.totems.signal('hit',e);g.player.inv=0;g.hurt(10,0);assert.equal(g.totems.states.cup.n,0);});
test('triangle has exclusive attack or defense branches and cooldown survives swapping',()=>{const g=setup(['triangle']),e=enemy(g);for(const k of ['hit','evade','hit','evade'])g.totems.signal(k,e);g.action('circuit');assert.equal(g.totems.guard,.4);assert.equal(g.totems.states.triangle.cd,14);const hp=g.player.hp;g.player.inv=0;g.hurt(10,0);assert.equal(g.player.hp,hp-6);g.state='totems';g.totems.unequip(0);g.totems.equip('triangle',0);assert.equal(g.totems.states.triangle.cd,14);g.totems.update(14,{});for(const k of ['hit','evade','hit','evade'])g.totems.signal(k,e);const ehp=e.hp;g.totems.signal('profit',e);assert.equal(e.hp,ehp-g.damage());assert.equal(g.totems.guard,0);});
test('pause freezes pattern timers; timeout and room transition invalidate progress',()=>{const g=setup(['cup']),e=enemy(g);g.totems.signal('hit',e);g.state='totems';g.update(1);assert.equal(g.totems.states.cup.time,10);g.state='playing';g.totems.update(11,{});assert.equal(g.totems.states.cup.n,0);g.totems.signal('hit',e);g.setRoom(1);assert.equal(g.totems.states.cup.n,0);assert.deepEqual(g.totems.slots,['cup',null,null]);});

test('exploration choices defer safely, reject invalid rewards and only grant once',()=>{const g=setup([]);g.player.x=g.relic.x-15;g.player.y=g.relic.y-28;g.checkRelicPickup();const offers=[...g.relic.offers];assert.equal(offers.length,2);assert.equal(new Set(offers).size,2);assert.equal(g.chooseRelic('seed'),false);assert.equal(g.chooseRelic('not-an-offer'),false);g.chooseRelic('leave');assert.equal(g.relic.taken,false);assert.equal(g.checkRelicPickup(),false);g.player.x-=100;g.checkRelicPickup();g.player.x+=100;g.checkRelicPickup();assert.deepEqual(g.relic.offers,offers);g.chooseRelic(offers[1]);assert.equal(g.totems.owned.length,1);assert.equal(g.chooseRelic(offers[0]),false);assert.equal(g.totems.owned.length,1);});
test('all-owned caches convert to seed once and upper branches preserve a floor route',()=>{const g=setup([]);for(const {id} of TOTEMS)g.totems.acquire(id);for(const room of [0,1,3,5,6,8]){g.setRoom(room);assert.deepEqual(g.relic.offers,[]);assert.equal(g.platforms[0].w,g.width);const [base,step,top]=g.platforms.slice(-3);assert.equal(base.y-step.y,96);assert.equal(step.y-top.y,92);assert.ok(top.x+top.w<g.width-180);assert.equal(top.y-25,g.relic.y);}g.relic.trialComplete=true;g.relic.revealed=true;g.player.x=g.relic.x-15;g.player.y=g.relic.y-28;g.checkRelicPickup();const gold=g.player.gold;assert.equal(g.chooseRelic('seed'),true);assert.equal(g.player.gold,gold+40);assert.equal(g.chooseRelic('seed'),false);});

test('walking into small chest opens once, misses from below, and stays consumed',()=>{
 const g=setup([]);g.player.x=g.relic.x-15;g.player.y=g.relic.y+30;
 assert.equal(g.checkRelicPickup(),false);
 g.player.y=g.relic.y-28;g.update(1/120);assert.equal(g.state,'relic_choice');
 assert.equal(g.totems.logs.filter(e=>e.event==='totem_offer_shown').length,1);
 g.chooseRelic(g.relic.offers[0]);g.state='playing';g.update(1/120);
 assert.equal(g.relic.taken,true);assert.equal(g.state,'playing');
});
