import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.mjs';
import {UPPER_SKILLS,segmentHit} from '../upper-boss.mjs';
import {drawUpperBoss} from '../upper-boss-art.mjs';
const make=room=>{const g=new Game({random:()=>.5});g.start();g.setRoom(room);g.player.inv=999;g.marketPeriod=999;const e=g.enemies[0];e.activated=true;e.timer=0;g.player.y=620-g.player.h;return [g,e];};
const step=(g,n,input={})=>{for(let i=0;i<n;i++)g.update(1/120,input);};
test('signatures are chapter-specific and start through real enemy dispatch',()=>{for(const [room,distance]of [[14,200],[19,260],[24,400]]){const [g,e]=make(room);g.player.x=e.x-distance;g.updateEnemy(e,.01);assert.equal(e.skillName,UPPER_SKILLS[e.type]);assert.equal(g.log.events.at(-1).pattern,e.skillName);}for(const room of [4,9,28]){const[g,e]=make(room);g.player.x=e.x-200;step(g,600);assert.equal(e.skillName,undefined);}});
test('axe leaps physically, locks target, lands once and exposes recovery',()=>{const[g,e]=make(19);g.player.x=e.x-300;step(g,95);assert.equal(e.skillState,'leap');assert.ok(e.y+e.h<600);const target=e.targetX;g.player.x=100;let impacts=0;g.onEvent=evt=>{if(evt.type==='sound'&&evt.name==='heavy-hit')impacts++;};step(g,160);assert.equal(e.targetX,target);assert.equal(e.skillState,'recover');assert.equal(impacts,1);assert.ok(Math.abs(e.x+e.w/2-target)<20);assert.equal(g.projectiles.length,0);});
function grab(inv=0){const[g,e]=make(14);e.skillActive=true;e.skillName='주식분할';e.skillState='grab';e.state='attack';e.timer=.3;e.lockDirection=1;g.player.x=e.x+e.w;g.player.y=e.y;g.player.inv=inv;g.updateEnemy(e,.01);return[g,e];}
test('grab checks invulnerability; successful hold blocks movement and ends with one damage event',()=>{let[g,e]=grab(1);assert.ok(!g.player.capture);[g,e]=grab();assert.ok(g.player.capture);const x=g.player.x,hp=g.player.hp;g.action('dash');g.action('jump');step(g,20,{right:true,attack:true});assert.equal(g.player.x,x);assert.equal(g.player.hp,hp);assert.equal(g.player.attackMove,null);step(g,60);assert.ok(!g.player.capture);assert.equal(g.log.events.filter(x=>x.event==='damage_taken').length,1);});
test('capture pauses, circuit breaks it, death and room changes clear it',()=>{for(const exit of ['circuit','boss','room','death']){const[g,e]=grab();g.state='paused';const time=g.player.capture.remaining;step(g,90);assert.equal(g.player.capture.remaining,time);g.state='playing';if(exit==='circuit'){g.action('circuit');step(g,1);}if(exit==='boss')g.hitEnemy(e,99999,0,false,true);if(exit==='room')g.setRoom(15);if(exit==='death')g.finish(false);assert.ok(!g.player.capture,exit);}});
test('sniper moves, locks aim, fires once and reloads',()=>{const[g,e]=make(24);g.player.x=e.x-450;const start=e.x;let found=false;for(let i=0;i<600;i++){g.update(1/120);if(e.skillState==='locked'){found=true;break;}}assert.ok(found);assert.notEqual(e.x,start);const shot={...e.shot};g.player.x=100;step(g,60);assert.deepEqual(e.shot,shot);assert.equal(e.skillState,'reload');assert.equal(g.projectiles.length,0);});
test('sniper shot hits on line, misses after dodge and is blocked by terrain',()=>{for(const mode of ['hit','dodge','wall']){const[g,e]=make(24);g.platforms=[g.platforms[0]];e.skillActive=true;e.skillState='locked';e.state='windup';e.timer=0;e.shot={x:100,y:590,dx:1800,dy:0};g.player.x=500;g.player.y=570;g.player.inv=mode==='dodge'?1:0;if(mode==='wall')g.platforms.push({x:300,y:500,w:50,h:120,solid:true});const hp=g.player.hp;g.updateEnemy(e,.01);assert.equal(g.player.hp<hp,mode==='hit');assert.ok(e.beam);}});
test('ray geometry handles parallel misses and hits without sampling',()=>{assert.equal(segmentHit(0,0,100,0,{x:20,y:-5,w:10,h:10}),.2);assert.equal(segmentHit(0,0,100,0,{x:20,y:5,w:10,h:10}),null);});
test('weapon renderer accepts every signature state without mutating combat',()=>{const ctx=new Proxy({}, {get:()=>()=>{},set:()=>true});for(const room of [14,19,24]){const[g,e]=make(room);for(const state of ['prepare','grab','split','leap','impact','reposition','aim','locked','reload','recover']){e.skillActive=true;e.skillState=state;e.targetX=500;e.aimX=500;e.aimY=500;e.timer=.2;e.shot={x:1,y:2,dx:3,dy:4};const before=JSON.stringify(e);drawUpperBoss(ctx,e);assert.equal(JSON.stringify(e),before);}}});
test('sniper selects reachable high ground without non-finite jump velocities',()=>{
 const[g,e]=make(24);g.player.x=e.x-450;
 g.platforms=[g.platforms[0],{x:e.x+150,y:414,w:240,h:18},{x:e.x-500,y:300,w:100,h:18}];
 step(g,45);assert.equal(e.skillState,'reposition');assert.ok(Number.isFinite(e.airSpeed));
 for(let i=0;i<240;i++){g.update(1/120);assert.ok(Number.isFinite(e.x)&&Number.isFinite(e.y));}
});
