import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.mjs';
import {wallSide,verticalCamera} from '../movement.mjs';
function setup(){const g=new Game();g.start();g.rewardGiven=true;g.relic=null;g.enemies=[];g.terrain.traps=[];g.platforms=[{x:0,y:620,w:2000,h:100,ground:true},{x:400,y:-200,w:64,h:820,solid:true}];Object.assign(g.player,{x:400-g.player.w,y:150,vy:500,grounded:false,inv:99});return g;}
test('wall slide caps descent, release restores gravity, ledges grant no wall contact',()=>{const g=setup();g.update(1/60,{right:true});assert.ok(g.player.wallSliding);assert.ok(g.player.vy<=120);g.update(1/60,{});assert.equal(g.player.wallSliding,false);assert.ok(g.player.vy>120);assert.equal(wallSide(g.player,[{x:400,y:0,w:64,h:600}]),0);});
test('wall jump pushes away despite held input and leaves one air jump',()=>{const g=setup();g.action('jump');g.update(1/60,{right:true});assert.ok(g.player.vx<0);assert.ok(g.player.vy<0);assert.ok(g.player.x<400-g.player.w);assert.equal(g.player.jumps,1);assert.equal(g.log.events.filter(e=>e.event==='wall_jump').length,1);g.action('jump');g.update(1/60,{});assert.equal(g.player.jumps,2);});
test('right face launches right, decorative walls cannot launch and pause freezes camera',()=>{const g=setup();g.player.x=464;g.action('jump');g.update(1/60,{left:true});assert.ok(g.player.vx>0);g.platforms[1].climbable=false;assert.equal(wallSide({...g.player,x:464,grounded:false},g.platforms),0);g.cameraY=-100;g.state='paused';g.update(.02);assert.equal(g.cameraY,-100);g.setRoom(2,false);assert.equal(g.cameraY,0);assert.equal(g.player.wallLock,0);});
test('camera follows upper space, looks ahead during falls and respects room limits',()=>{const body={y:-200,h:33,vy:0};let y=0;for(let i=0;i<120;i++)y=verticalCamera(y,body,-360,1/60);assert.ok(y< -300);const fall=verticalCamera(-300,{...body,y:150,vy:800},-360,1/60);const still=verticalCamera(-300,{...body,y:150,vy:0},-360,1/60);assert.ok(fall>still);assert.equal(verticalCamera(0,{...body,y:600,vy:900},-360,.1),0);assert.equal(verticalCamera(0,body,70,.1),0);});
test('player can rise past former screen ceiling within room world bounds',()=>{const g=setup();g.player.y=75;g.player.vy=-550;g.update(1/60,{});assert.ok(g.player.y<70);g.player.y=-365;g.update(1/60,{});assert.equal(g.player.y,-360);});
